default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: flight_booker_development

test:
  <<: *default
  database: flight_booker_test

production:
  <<: *default
  database: flight_booker_production
